// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: pkg/proto/adapter.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiateMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitiateMigrationRequest) Reset() {
	*x = InitiateMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitiateMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMigrationRequest) ProtoMessage() {}

func (x *InitiateMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMigrationRequest.ProtoReflect.Descriptor instead.
func (*InitiateMigrationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{0}
}

type InitiateMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitiateMigrationResponse) Reset() {
	*x = InitiateMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitiateMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMigrationResponse) ProtoMessage() {}

func (x *InitiateMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMigrationResponse.ProtoReflect.Descriptor instead.
func (*InitiateMigrationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{1}
}

type TransitCheckpointRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TransitCheckpointRequest) Reset() {
	*x = TransitCheckpointRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransitCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitCheckpointRequest) ProtoMessage() {}

func (x *TransitCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitCheckpointRequest.ProtoReflect.Descriptor instead.
func (*TransitCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{2}
}

type TransitCheckpointResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TransitCheckpointResponse) Reset() {
	*x = TransitCheckpointResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransitCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitCheckpointResponse) ProtoMessage() {}

func (x *TransitCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitCheckpointResponse.ProtoReflect.Descriptor instead.
func (*TransitCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{3}
}

type ExchangestatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ExchangestatusRequest) Reset() {
	*x = ExchangestatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangestatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangestatusRequest) ProtoMessage() {}

func (x *ExchangestatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangestatusRequest.ProtoReflect.Descriptor instead.
func (*ExchangestatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{4}
}

func (x *ExchangestatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ExchangeStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ExchangeStatusResponse) Reset() {
	*x = ExchangeStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeStatusResponse) ProtoMessage() {}

func (x *ExchangeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeStatusResponse.ProtoReflect.Descriptor instead.
func (*ExchangeStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{5}
}

func (x *ExchangeStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ShouldCloseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShouldCloseRequest) Reset() {
	*x = ShouldCloseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShouldCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShouldCloseRequest) ProtoMessage() {}

func (x *ShouldCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShouldCloseRequest.ProtoReflect.Descriptor instead.
func (*ShouldCloseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{6}
}

type ShouldCloseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShouldCloseResponse) Reset() {
	*x = ShouldCloseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShouldCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShouldCloseResponse) ProtoMessage() {}

func (x *ShouldCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShouldCloseResponse.ProtoReflect.Descriptor instead.
func (*ShouldCloseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{7}
}

var File_pkg_proto_adapter_proto protoreflect.FileDescriptor

var file_pkg_proto_adapter_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x64, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x64, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x22, 0x1a, 0x0a, 0x18, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1b,
	0x0a, 0x19, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2f, 0x0a, 0x15, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x30, 0x0a, 0x16, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x75, 0x6c,
	0x64, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a,
	0x13, 0x53, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xe5, 0x02, 0x0a, 0x08, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x12, 0x5a, 0x0a, 0x11, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x64, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a,
	0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x12, 0x21, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x51, 0x0a,
	0x0e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1e, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4a, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12,
	0x1b, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x75, 0x6c, 0x64,
	0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61,
	0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x15, 0x5a, 0x13,
	0x2e, 0x2f, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_adapter_proto_rawDescOnce sync.Once
	file_pkg_proto_adapter_proto_rawDescData = file_pkg_proto_adapter_proto_rawDesc
)

func file_pkg_proto_adapter_proto_rawDescGZIP() []byte {
	file_pkg_proto_adapter_proto_rawDescOnce.Do(func() {
		file_pkg_proto_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_adapter_proto_rawDescData)
	})
	return file_pkg_proto_adapter_proto_rawDescData
}

var file_pkg_proto_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_proto_adapter_proto_goTypes = []interface{}{
	(*InitiateMigrationRequest)(nil),  // 0: adapter.InitiateMigrationRequest
	(*InitiateMigrationResponse)(nil), // 1: adapter.InitiateMigrationResponse
	(*TransitCheckpointRequest)(nil),  // 2: adapter.TransitCheckpointRequest
	(*TransitCheckpointResponse)(nil), // 3: adapter.TransitCheckpointResponse
	(*ExchangestatusRequest)(nil),     // 4: adapter.ExchangestatusRequest
	(*ExchangeStatusResponse)(nil),    // 5: adapter.ExchangeStatusResponse
	(*ShouldCloseRequest)(nil),        // 6: adapter.ShouldCloseRequest
	(*ShouldCloseResponse)(nil),       // 7: adapter.ShouldCloseResponse
}
var file_pkg_proto_adapter_proto_depIdxs = []int32{
	0, // 0: adapter.Migrator.InitiateMigration:input_type -> adapter.InitiateMigrationRequest
	2, // 1: adapter.Migrator.TransitCheckpoint:input_type -> adapter.TransitCheckpointRequest
	4, // 2: adapter.Migrator.ExchangeStatus:input_type -> adapter.ExchangestatusRequest
	6, // 3: adapter.Migrator.ShouldClose:input_type -> adapter.ShouldCloseRequest
	1, // 4: adapter.Migrator.InitiateMigration:output_type -> adapter.InitiateMigrationResponse
	3, // 5: adapter.Migrator.TransitCheckpoint:output_type -> adapter.TransitCheckpointResponse
	5, // 6: adapter.Migrator.ExchangeStatus:output_type -> adapter.ExchangeStatusResponse
	7, // 7: adapter.Migrator.ShouldClose:output_type -> adapter.ShouldCloseResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_adapter_proto_init() }
func file_pkg_proto_adapter_proto_init() {
	if File_pkg_proto_adapter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_adapter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitiateMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_adapter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitiateMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_adapter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransitCheckpointRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_adapter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransitCheckpointResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_adapter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangestatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_adapter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_adapter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShouldCloseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_adapter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShouldCloseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_adapter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_adapter_proto_goTypes,
		DependencyIndexes: file_pkg_proto_adapter_proto_depIdxs,
		MessageInfos:      file_pkg_proto_adapter_proto_msgTypes,
	}.Build()
	File_pkg_proto_adapter_proto = out.File
	file_pkg_proto_adapter_proto_rawDesc = nil
	file_pkg_proto_adapter_proto_goTypes = nil
	file_pkg_proto_adapter_proto_depIdxs = nil
}
