// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: pkg/proto/adapter.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiateMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodName      string   `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace string   `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	Containers   []string `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
}

func (x *InitiateMigrationRequest) Reset() {
	*x = InitiateMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitiateMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMigrationRequest) ProtoMessage() {}

func (x *InitiateMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMigrationRequest.ProtoReflect.Descriptor instead.
func (*InitiateMigrationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateMigrationRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *InitiateMigrationRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *InitiateMigrationRequest) GetContainers() []string {
	if x != nil {
		return x.Containers
	}
	return nil
}

type InitiateMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitiateMigrationResponse) Reset() {
	*x = InitiateMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitiateMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMigrationResponse) ProtoMessage() {}

func (x *InitiateMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMigrationResponse.ProtoReflect.Descriptor instead.
func (*InitiateMigrationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{1}
}

type TransitCheckpointInformationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TransitCheckpointInformationRequest) Reset() {
	*x = TransitCheckpointInformationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransitCheckpointInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitCheckpointInformationRequest) ProtoMessage() {}

func (x *TransitCheckpointInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitCheckpointInformationRequest.ProtoReflect.Descriptor instead.
func (*TransitCheckpointInformationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{2}
}

type TransitCheckpointInformationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TransitCheckpointInformationResponse) Reset() {
	*x = TransitCheckpointInformationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransitCheckpointInformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitCheckpointInformationResponse) ProtoMessage() {}

func (x *TransitCheckpointInformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitCheckpointInformationResponse.ProtoReflect.Descriptor instead.
func (*TransitCheckpointInformationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{3}
}

type TransotCheckpointFragmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckpointIndex int64  `protobuf:"varint,1,opt,name=checkpoint_index,json=checkpointIndex,proto3" json:"checkpoint_index,omitempty"`
	FragmentIndex   int64  `protobuf:"varint,2,opt,name=fragment_index,json=fragmentIndex,proto3" json:"fragment_index,omitempty"`
	Payload         []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *TransotCheckpointFragmentRequest) Reset() {
	*x = TransotCheckpointFragmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransotCheckpointFragmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransotCheckpointFragmentRequest) ProtoMessage() {}

func (x *TransotCheckpointFragmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransotCheckpointFragmentRequest.ProtoReflect.Descriptor instead.
func (*TransotCheckpointFragmentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{4}
}

func (x *TransotCheckpointFragmentRequest) GetCheckpointIndex() int64 {
	if x != nil {
		return x.CheckpointIndex
	}
	return 0
}

func (x *TransotCheckpointFragmentRequest) GetFragmentIndex() int64 {
	if x != nil {
		return x.FragmentIndex
	}
	return 0
}

func (x *TransotCheckpointFragmentRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TransotCheckpointFragmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckpointIndex int64 `protobuf:"varint,1,opt,name=checkpoint_index,json=checkpointIndex,proto3" json:"checkpoint_index,omitempty"`
	FragmentIndex   int64 `protobuf:"varint,2,opt,name=fragment_index,json=fragmentIndex,proto3" json:"fragment_index,omitempty"`
}

func (x *TransotCheckpointFragmentResponse) Reset() {
	*x = TransotCheckpointFragmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransotCheckpointFragmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransotCheckpointFragmentResponse) ProtoMessage() {}

func (x *TransotCheckpointFragmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransotCheckpointFragmentResponse.ProtoReflect.Descriptor instead.
func (*TransotCheckpointFragmentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{5}
}

func (x *TransotCheckpointFragmentResponse) GetCheckpointIndex() int64 {
	if x != nil {
		return x.CheckpointIndex
	}
	return 0
}

func (x *TransotCheckpointFragmentResponse) GetFragmentIndex() int64 {
	if x != nil {
		return x.FragmentIndex
	}
	return 0
}

type ExchangestatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ExchangestatusRequest) Reset() {
	*x = ExchangestatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangestatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangestatusRequest) ProtoMessage() {}

func (x *ExchangestatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangestatusRequest.ProtoReflect.Descriptor instead.
func (*ExchangestatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{6}
}

func (x *ExchangestatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ExchangeStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ExchangeStatusResponse) Reset() {
	*x = ExchangeStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeStatusResponse) ProtoMessage() {}

func (x *ExchangeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeStatusResponse.ProtoReflect.Descriptor instead.
func (*ExchangeStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{7}
}

func (x *ExchangeStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ShouldCloseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShouldCloseRequest) Reset() {
	*x = ShouldCloseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShouldCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShouldCloseRequest) ProtoMessage() {}

func (x *ShouldCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShouldCloseRequest.ProtoReflect.Descriptor instead.
func (*ShouldCloseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{8}
}

type ShouldCloseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShouldCloseResponse) Reset() {
	*x = ShouldCloseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_adapter_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShouldCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShouldCloseResponse) ProtoMessage() {}

func (x *ShouldCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_adapter_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShouldCloseResponse.ProtoReflect.Descriptor instead.
func (*ShouldCloseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_adapter_proto_rawDescGZIP(), []int{9}
}

var File_pkg_proto_adapter_proto protoreflect.FileDescriptor

var file_pkg_proto_adapter_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x64, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x64, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x22, 0x7a, 0x0a, 0x18, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x70, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6f, 0x64,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x1b,
	0x0a, 0x19, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x0a, 0x23, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x26, 0x0a, 0x24, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x20, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6f, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x29, 0x0a, 0x10, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x72,
	0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x75, 0x0a, 0x21, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6f, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x29, 0x0a, 0x10, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x25, 0x0a, 0x0e, 0x66,
	0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0d, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x22, 0x2f, 0x0a, 0x15, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x30, 0x0a, 0x16, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x53,
	0x68, 0x6f, 0x75, 0x6c, 0x64, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0xfa, 0x03, 0x0a, 0x08, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12,
	0x5a, 0x0a, 0x11, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x49,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7b, 0x0a, 0x1c, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x2e, 0x61, 0x64,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x61, 0x64, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x76, 0x0a, 0x19, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x6f, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x46, 0x72, 0x61,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x29, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x6f, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2a, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x6f, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x46, 0x72, 0x61, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x51, 0x0a, 0x0e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1e, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x12, 0x1b, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f,
	0x75, 0x6c, 0x64, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x75, 0x6c, 0x64,
	0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42,
	0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_adapter_proto_rawDescOnce sync.Once
	file_pkg_proto_adapter_proto_rawDescData = file_pkg_proto_adapter_proto_rawDesc
)

func file_pkg_proto_adapter_proto_rawDescGZIP() []byte {
	file_pkg_proto_adapter_proto_rawDescOnce.Do(func() {
		file_pkg_proto_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_adapter_proto_rawDescData)
	})
	return file_pkg_proto_adapter_proto_rawDescData
}

var file_pkg_proto_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_proto_adapter_proto_goTypes = []interface{}{
	(*InitiateMigrationRequest)(nil),             // 0: adapter.InitiateMigrationRequest
	(*InitiateMigrationResponse)(nil),            // 1: adapter.InitiateMigrationResponse
	(*TransitCheckpointInformationRequest)(nil),  // 2: adapter.TransitCheckpointInformationRequest
	(*TransitCheckpointInformationResponse)(nil), // 3: adapter.TransitCheckpointInformationResponse
	(*TransotCheckpointFragmentRequest)(nil),     // 4: adapter.TransotCheckpointFragmentRequest
	(*TransotCheckpointFragmentResponse)(nil),    // 5: adapter.TransotCheckpointFragmentResponse
	(*ExchangestatusRequest)(nil),                // 6: adapter.ExchangestatusRequest
	(*ExchangeStatusResponse)(nil),               // 7: adapter.ExchangeStatusResponse
	(*ShouldCloseRequest)(nil),                   // 8: adapter.ShouldCloseRequest
	(*ShouldCloseResponse)(nil),                  // 9: adapter.ShouldCloseResponse
}
var file_pkg_proto_adapter_proto_depIdxs = []int32{
	0, // 0: adapter.Migrator.InitiateMigration:input_type -> adapter.InitiateMigrationRequest
	2, // 1: adapter.Migrator.TransitCheckpointInformation:input_type -> adapter.TransitCheckpointInformationRequest
	4, // 2: adapter.Migrator.TransotCheckpointFragment:input_type -> adapter.TransotCheckpointFragmentRequest
	6, // 3: adapter.Migrator.ExchangeStatus:input_type -> adapter.ExchangestatusRequest
	8, // 4: adapter.Migrator.ShouldClose:input_type -> adapter.ShouldCloseRequest
	1, // 5: adapter.Migrator.InitiateMigration:output_type -> adapter.InitiateMigrationResponse
	3, // 6: adapter.Migrator.TransitCheckpointInformation:output_type -> adapter.TransitCheckpointInformationResponse
	5, // 7: adapter.Migrator.TransotCheckpointFragment:output_type -> adapter.TransotCheckpointFragmentResponse
	7, // 8: adapter.Migrator.ExchangeStatus:output_type -> adapter.ExchangeStatusResponse
	9, // 9: adapter.Migrator.ShouldClose:output_type -> adapter.ShouldCloseResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_adapter_proto_init() }
func file_pkg_proto_adapter_proto_init() {
	if File_pkg_proto_adapter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_adapter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitiateMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_adapter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitiateMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_adapter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransitCheckpointInformationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_adapter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransitCheckpointInformationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_adapter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransotCheckpointFragmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_adapter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransotCheckpointFragmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_adapter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangestatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_adapter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_adapter_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShouldCloseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_adapter_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShouldCloseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_adapter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_adapter_proto_goTypes,
		DependencyIndexes: file_pkg_proto_adapter_proto_depIdxs,
		MessageInfos:      file_pkg_proto_adapter_proto_msgTypes,
	}.Build()
	File_pkg_proto_adapter_proto = out.File
	file_pkg_proto_adapter_proto_rawDesc = nil
	file_pkg_proto_adapter_proto_goTypes = nil
	file_pkg_proto_adapter_proto_depIdxs = nil
}
