# permissions for end users to edit lpmjobrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: lpmjobrequest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lpm-mpod-controller
    app.kubernetes.io/part-of: lpm-mpod-controller
    app.kubernetes.io/managed-by: kustomize
  name: lpmjobrequest-editor-role
rules:
- apiGroups:
  - lpm.edgenet.io
  resources:
  - lpmjobrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lpm.edgenet.io
  resources:
  - lpmjobrequests/status
  verbs:
  - get
