# permissions for end users to view lpmjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: lpmjob-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: live-pod-migration
    app.kubernetes.io/part-of: live-pod-migration
    app.kubernetes.io/managed-by: kustomize
  name: lpmjob-viewer-role
rules:
- apiGroups:
  - lpm.edgenet.io.my.domain
  resources:
  - lpmjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lpm.edgenet.io.my.domain
  resources:
  - lpmjobs/status
  verbs:
  - get
