apiVersion: lpm.edgenet.io.my.domain/v1alpha1
kind: LPMJobRequest
metadata:
  labels:
    app.kubernetes.io/name: lpmjobrequest
    app.kubernetes.io/instance: lpmjobrequest-sample
    app.kubernetes.io/part-of: lpm-mpod-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: lpm-mpod-controller
  name: lpmjobrequest-sample
spec:
  # TODO(user): Add fields here
