apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: migrationpods.lpm.edgenet.io
spec:
  group: lpm.edgenet.io
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                containers:
                  type: array
                  items:
                    type: object
                    properties:
                      containerName: 
                        type: string
                      containerImage:
                        type: string
  names:
    kind: MigrationPod
    singular: migrationpod
    plural: migrationpods
    shortNames:
      - mpods
      - mpod
      - mp
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lpmjobrequests.lpm.edgenet.io
spec:
  group: lpm.edgenet.io
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              nullable: false
              required:
               - podName
               - nodeName
              properties:
                podName:
                  type: string
                  nullable: false
                nodeName:
                  type: string
                  nullable: false
            status:
              type: object
              nullable: true
              properties:
                accepted:
                  type: boolean
                errorString:
                  type: string
  names:
    kind: LPMJobRequest
    singular: lpmjobrequest
    plural: lpmjobrequests
    shortNames:
      - lpmr
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lpmjobs.lpm.edgenet.io
spec:
  group: lpm.edgenet.io
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sourcePodName:
                  type: string
                  nullable: false
                destinationPodName:
                  type: string
                  nullable: false
                sourceNodeName:
                  type: string
                  nullable: false
                destinationNodeName:
                  type: string
                  nullable: false
                sourceNodeIP:
                  type: string
                  nullable: false
                destinationNodeIP:
                  type: string
                  nullable: false
                migrationStatus:
                  type: string
                  nullable: false
                  enum:
                    - Processing
                    - Checkpointing
                    - Transfering
                    - Restoring
                    - Cleaning
                    - Done
                    - Error
                numberOfContainers:
                  type: integer
                  nullable: false
                  minimum: 1
                containerStatuses:
                  type: array
                  nullable: false
                  items:
                    type: object
                    nullable: false
                    required:
                      - containerId
                      - migrationStatus
                    properties:
                      containerId:
                        type: string
                        nullable: false
                      migrationStatus:
                        type: string
                        nullable: false
            status:
              type: object
              nullable: true
              properties:
                accepted:
                  type: boolean
                errorString:
                  type: string
  names:
    kind: LPMJob
    singular: lpmjob
    plural: lpmjobs
    shortNames:
      - lpm